### ISSUE TITLE
Create zig binding auto generator from header file

### ISSUE THREAD

**Issue by ryoppippi** [ryoppippi/zigcv#2]
Currently, zigcv reads and uses gocv header files, but this does not allow function name and type completion on the editor. ralib-zig would like to generate zig code from c header files, like ralib-zig.

There are two options

-  auto-generation from go files
-  auto-generation from c header files

**Comment by ryoppippi** [comment]
I changed my mind and have started zig bindings.
It is good for all zig user

**Comment by jingsupo** [comment]
good job! 👍
